version: '2.1'

services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.1.1
    hostname: zoo1
    container_name: zoo1
    networks:
      priv_net:
        ipv4_address: 172.20.0.4
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.1.1
    hostname: kafka1
    container_name: kafka1
    networks:
      priv_net:
        ipv4_address: 172.20.0.5
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: 172.20.0.5
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1

  postgres:
    image: cinghio/tm-databases:0.1
    hostname: postgres
    container_name: postgres
    networks:
      priv_net:
        ipv4_address: 172.20.0.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "prova"

  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    networks:
      priv_net:
        ipv4_address: 172.20.0.2
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "prova"

  trust-monitor:
      image: cinghio/trust-monitor:0.11
      hostname: trust-monitor
      container_name: trust-monitor
      networks:
        priv_net:
          ipv4_address: 172.20.0.10
      ports:
        - "5080:5080"
      depends_on:
        - kafka1
        - postgres
        - mongo
      volumes:
        - '../:/var/log/trust-monitor'

  tm-gui:
      image: cinghio/tm-gui:0.5
      hostname: tm-gui
      container_name: tm-gui
      networks:
        priv_net:
          ipv4_address: 172.20.0.11
      ports:
        - "8080:80"
      depends_on:
        - trust-monitor

networks:
    priv_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - 
                  subnet: 172.20.0.0/24