apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: keylime-registrar
  name: keylime-registrar
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keylime-registrar
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: keylime-registrar
    spec:
      containers:
        - image: cinghio/keylime_registrar:latest
          imagePullPolicy: Always
          name: keylime-registrar
          ports:
            - containerPort: 8890
            - containerPort: 8891
          resources: {}
      hostname: keylime-registrar
      restartPolicy: Always
