apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: keylime-webapp
  name: keylime-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keylime-webapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: keylime-webapp
    spec:
      containers:
        - image: cinghio/keylime_webapp:latest
          imagePullPolicy: IfNotPresent
          name: keylime-webapp
          ports:
            - containerPort: 443
          resources: {}
      hostname: keylime-webapp
      restartPolicy: Always
