apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka1
  name: kafka1
spec:
  ports:
  - name: port-1
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: port-2
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    io.kompose.service: kafka1
  sessionAffinity: None
  type: ClusterIP
