apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: tm-gui
  name: tm-gui
spec:
  ports:
  - nodePort: 32008
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    io.kompose.service: tm-gui
  sessionAffinity: None
  type: NodePort
