apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: tm-gui
  name: tm-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tm-gui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: tm-gui
    spec:
      containers:
        - image: cinghio/tm-gui:0.11
          name: tm-gui
          ports:
            - containerPort: 443
          resources: {}
      hostname: tm-gui
      restartPolicy: Always
status: {}
