apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: trust-monitor
  name: trust-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trust-monitor
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: trust-monitor
    spec:
      containers:
        - image: cinghio/trust-monitor:0.5
          name: trust-monitor
          ports:
            - containerPort: 5080
          resources: {}
          volumeMounts:
            - mountPath: /var/log/trust-monitor
              name: trust-monitor-claim0
            - mountPath: /trust-monitor/config
              name: trust-monitor-claim0
      hostname: trust-monitor
      restartPolicy: Always
      volumes:
        - name: trust-monitor-claim0
          persistentVolumeClaim:
            claimName: trust-monitor-claim0
status: {}
