apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: zoo1
  name: zoo1
spec:
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    io.kompose.service: zoo1
  sessionAffinity: None
  type: ClusterIP
